org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.17.2

# Fabric API
fabric_version=0.131.0+1.21.8

modmenu_version=12.0.0
clothconfig_version=16.0.141
rei_version=17.0.790

mod_version = 1.2.2-SNAPSHOT
maven_group = zabi.minecraft.nbttooltip
archives_base_name = nbttooltip